version: '2'

services:
  mongo:
    image: mongo
    command: mongod --smallfiles --quiet
    ports:
      - "27017:27017"

  website:
    depends_on:
      - 'mongo'
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/pdvend_products'
    env_file:
      - '.env'

volumes:
  mongo:
