version: '2'

services:
  mongo:
    image: mongo
    command: mongod --smallfiles --quiet
    ports:
      - "27017:27017"

  redis:
    image: redis:3.2-alpine
    command: redis-server
    ports:
      - '6379:6379'

  jobs:
    depends_on:
      - 'mongo'
      - 'redis'
      - 'website'
    build: .
    command: bash start_jobs
    volumes:
      - '.:/pdvend_products'
    env_file:
      - '.env'

  website:
    depends_on:
      - 'mongo'
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/pdvend_products'
    env_file:
      - '.env'

volumes:
  mongo:
